### PR TITLE
Merge last weeks works - New features added

### PR DESCRIPTION
**Pull request by Jo-zTk**
## Purpose
__Because we didn't respect atomic PR we have many features to merge now. But we have tried to used atomic commit, and to keep a clear view of what has been done, each commit describe clearly what has been done using a comprehensive description like this : "Feat/Security: Add guard services...."__

- Readme has been modified
- Website title has been changed to match the project
- All non logged users will not be able to play game (Guard services configured)
- The game table is shown in the lobby before playing
- New component has been configured to welcome players after they wait in the lobby
- Matchmaking is configured using Firebase, and works as expected

## Approach
This change improve experience by adding new features has describe above.

#### Open Questions and Pre-Merge TODOs
- [ ] Use github checklists. When solved, check the box and explain the answer.

## Learning
We have used official Angular and Firebase documentation

#### Blog Posts
- [How to Pull Request](https://github.com/flexyford/pull-request) Github Repo with Learning focused Pull Request Template.

## TO VALID PR

* All commits, vars, documentation, code are in English
* 1 feature = 1 PR, No more
* The code builds with Travis CI, and nothing looks unfinished
* When code is complicated, that’s documented, otherwise ask for comment 
* No node_modules is present
* Code respect [Airbnb style](https://hackernoon.com/configure-eslint-prettier-and-flow-in-vs-code-for-react-development-c9d95db07213) checked with Travis CI
* README explain Clearly how to run the project, otherwise reject the PR
* Chrome LightHouse CI score is upper than 80%

### CODE REVIEW

**Review by AvelJonathan — APPROVED** [review]
As we worked together on the project, i agree on most of the changes ! 

The only commit i would like to comment is concerning the commit "Fix issue redirect player 1" , as he's the only one commit we didn't work on as a group.

 I guess the 'onSnapshot function' into the promise let the player1 follow the player2 into the room when the player2 clicked on the play button, so i validate this one !

**Review by AnnaFlourou — APPROVED** [review]
This app updates review allows to show how the project is spreading up. 
I approve.

**Review by riderx — CHANGES_REQUESTED** [review]
I can't test the Pr on ghpages, deploy fail :/

**Review by Jo-zTk — COMMENTED** [review]
Add comment to fix these error messages : 

ERROR in src/app/profil/profil.component.html(2,20): : Property 'authService' is private and only accessible within class 'ProfilComponent'.
src/app/ingame/ingame.component.html(22,11): : Property 'isClicked' does not exist on type 'IngameComponent'.

**Review by alexandrecoin — APPROVED** [review]
Lots of changes (like many of us) but the requirements appear to be met.

**Review by BertrandBurel — APPROVED** [review]
OK.

**Review by MaximeSaliou72 — APPROVED** [review]

**Review by ChristianDanielMezieres — APPROVED** [review]
good guys !  :)

**Review by riderx — APPROVED** [review]

**Pull request merged**
