### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Jo-zTk**
## Purpose
**New Features :** 
- Ingame live score has been added
- Chatbox has been added
- Ingame display now the if it's your turn or not
- Add function to quit the game even if the game has started

**Design** :
- Style and HTML has been improved

**Clean** :
- Code has been cleaned

## Approach
These changes improve UX

#### Open Questions and Pre-Merge TODOs
- [ ] Use github checklists. When solved, check the box and explain the answer.

## Learning
Official Angular and Firebase documention

_Links to blog posts, patterns, libraries or addons used to solve this problem_

#### Blog Posts
- [How to Pull Request](https://github.com/flexyford/pull-request) Github Repo with Learning focused Pull Request Template.

## TO VALID PR

* All commits, vars, documentation, code are in English
* 1 feature = 1 PR, No more
* The code builds with Travis CI, and nothing looks unfinished
* When code is complicated, that’s documented, otherwise ask for comment 
* No node_modules is present
* Code respect [Airbnb style](https://hackernoon.com/configure-eslint-prettier-and-flow-in-vs-code-for-react-development-c9d95db07213) checked with Travis CI
* README explain Clearly how to run the project, otherwise reject the PR
* Chrome LightHouse CI score is upper than 80%

### CODE REVIEW

**Review by AnnaFlourou — APPROVED** [review]
Those new features and fixed bugs seem good to me. Our project has made a step ! well done partners !

**Review by alexandrecoin — APPROVED** [review]
Changes are up and running. Good job.

**Review by BenbachirAzzedine — APPROVED** [review]
all good !!

**Review by ctoxy — APPROVED** [review]
ok pour moi

**Review by AurelieAvisse — APPROVED** [review]

**Pull request merged**
