### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Jo-zTk**
## Purpose
Add structure HTML/CSS
Add Google Auth

## Approach
First PR

#### Open Questions and Pre-Merge TODOs
- [ ] Use github checklists. When solved, check the box and explain the answer.

## Learning
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

#### Blog Posts
- [How to Pull Request](https://github.com/flexyford/pull-request) Github Repo with Learning focused Pull Request Template.

## TO VALID PR

* All commits, vars, documentation, code are in English
* 1 feature = 1 PR, No more
* The code builds with Travis CI, and nothing looks unfinished
* When code is complicated, that’s documented, otherwise ask for comment 
* No node_modules is present
* Code respect [Airbnb style](https://hackernoon.com/configure-eslint-prettier-and-flow-in-vs-code-for-react-development-c9d95db07213) checked with Travis CI
* README explain Clearly how to run the project, otherwise reject the PR
* Chrome LightHouse CI score is upper than 80%

### CODE REVIEW

**Review by AvelJonathan — APPROVED** [review]
As part of the project, i'm ok with  this pull request, concerning the base structure of the project we work on together !
 Well done !

**Review by AnnaFlourou — APPROVED** [review]
According to me, your first pull request targets most of your objectives ! good job !

**Review by AurelieAvisse — APPROVED** [review]

**Comment by TheCodingLady** [comment]
I can see your site passed the tests.  Bravissimo to all of you :-)

**Review by TheCodingLady — APPROVED** [review]
looks good!

**Review by Laurentlcs — APPROVED** [review]

**Pull request merged**
